working_directory = "None"

[colors.bright]
black = "0x928374"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfabd2f"

[colors.normal]
black = "0x282828"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0xa89984"
yellow = "0xd79921"

[colors.primary]
background = "0x1d2021"
foreground = "0xebdbb2"

[cursor]
blink_interval = 300
thickness = 0.15
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.offset]
x = -1
y = 0

[[keyboard.bindings]]
action = "ClearHistory"
key = "K"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "Last"
key = 4
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "Open"
key = "O"
mode = "Vi"
mods = "alt"

[[keyboard.bindings]]
action = "Last"
key = "Key9"
mode = "Vi|~Search"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 1000
multiplier = 10

[selection]
save_to_clipboard = false

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_padding = true
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 100
lines = 40


[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 0
